### ISSUE TITLE
如何把project_matrix生成一个查找表

### ISSUE THREAD

**Issue by lhgen** [JokerEyeAdas/AdasSourrondView#2]
如何如何把project_matrix生成一个查找表？如何和前面的矫正mapx合起来就可以得到一个直接从原始画面到投影画面的查找表？

**Comment by JokerEyeAdas** [comment]
我理解搞一个map就可以了吧？相机方向字符串对应查找表

**Comment by lhgen** [comment]
找到了一个文档
https://blog.csdn.net/qq_18076309/article/details/128387175?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22128387175%22%2C%22source%22%3A%22unlogin%22%7D

**Comment by hopef** [comment]
https://github.com/zhangyeyan/360-Surround-View-CUDA-Project
这个应该跟你说的一样
